# Generated by Django 5.2.1 on 2025-07-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/students/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='people.students')),
            ],
            options={
                'db_table': 'StudentProfiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profiles/teachers/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='people.teachers')),
            ],
            options={
                'db_table': 'TeacherProfiles',
            },
        ),
    ]
